In [1]:
import seaborn as sb

In [5]:
planets = sb.load_dataset("planets") # Existe un dataset que se llama planets

In [6]:
planets.shape # Vamos a ver los datos: 1035 planetas, y 6 tipos de variables

(1035, 6)

In [58]:
planets.head(40)

                       method  number  orbital_period    mass  distance  year
0             Radial Velocity       1      269.300000   7.100     77.40  2006
1             Radial Velocity       1      874.774000   2.210     56.95  2008
2             Radial Velocity       1      763.000000   2.600     19.84  2011
3             Radial Velocity       1      326.030000  19.400    110.62  2007
4             Radial Velocity       1      516.220000  10.500    119.47  2009
5             Radial Velocity       1      185.840000   4.800     76.39  2008
6             Radial Velocity       1     1773.400000   4.640     18.15  2002
7             Radial Velocity       1      798.500000     NaN     21.41  1996
8             Radial Velocity       1      993.300000  10.300     73.10  2008
9             Radial Velocity       2      452.800000   1.990     74.79  2010
10            Radial Velocity       2      883.000000   0.860     74.79  2010
11            Radial Velocity       1      335.100000   9.880     39.43  2009
12            Radial Velocity       1      479.100000   3.880     97.28  2008
13            Radial Velocity       3     1078.000000   2.530     14.08  1996
14            Radial Velocity       3     2391.000000   0.540     14.08  2001
15            Radial Velocity       3    14002.000000   1.640     14.08  2009
16            Radial Velocity       1        4.230785   0.472     15.36  1995
17            Radial Velocity       5       14.651000   0.800     12.53  1996
18            Radial Velocity       5       44.380000   0.165     12.53  2004
19            Radial Velocity       5     4909.000000   3.530     12.53  2002
20            Radial Velocity       5        0.736540     NaN     12.53  2011
21            Radial Velocity       5      261.200000   0.172     12.53  2007
22            Radial Velocity       3        4.215000   0.016      8.52  2009
23            Radial Velocity       3       38.021000   0.057      8.52  2009
24            Radial Velocity       3      123.010000   0.072      8.52  2009
25            Radial Velocity       1      116.688400     NaN     18.11  1996
26            Radial Velocity       1      691.900000     NaN     81.50  2012
27            Radial Velocity       1      952.700000   5.300     97.18  2008
28            Radial Velocity       1      181.400000   3.200     45.52  2013
29                    Imaging       1             NaN     NaN     45.52  2005
30                    Imaging       1             NaN     NaN    165.00  2007
31                    Imaging       1             NaN     NaN    140.00  2004
32  Eclipse Timing Variations       1    10220.000000   6.050       NaN  2009
33                    Imaging       1             NaN     NaN       NaN  2008
34                    Imaging       1             NaN     NaN    145.00  2013
35                    Imaging       1             NaN     NaN    139.00  2004
36                    Imaging       1             NaN     NaN     18.39  2006
37  Eclipse Timing Variations       2     5767.000000     NaN    130.72  2008
38  Eclipse Timing Variations       2     3321.000000     NaN    130.72  2008
39  Eclipse Timing Variations       2     5573.550000     NaN    500.00  2010

In [10]:
planets.describe() # en Describe sacamos info del data frame
# en count, en este caso, CLARAMENTE vemos que hay muchos datos Nullos o NAN en "COUNT" porque la suma total de la linea
# debería ser igual en todas (LA LINEA "Count")

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [11]:
planets.dropna().describe()

          number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [12]:
planets.shape

(1035, 6)

In [13]:
planets_clean = planets.dropna().describe() # esta variable ya se podría utilizar como una tambla sin NANs

In [14]:
planets_clean.shape

(8, 5)

In [17]:
planets.distance.max()

8500.0

In [18]:
planets["distance"].max()

8500.0

In [19]:
planets.distance.std()

733.1164929404422

In [24]:
# Agrupaciones de años por "method" , para ver la primera vez que se usó cada uno

In [25]:
planets.groupby("method")["year"].min()

method
Astrometry                       2010
Eclipse Timing Variations        2008
Imaging                          2004
Microlensing                     2004
Orbital Brightness Modulation    2011
Pulsar Timing                    1992
Pulsation Timing Variations      2007
Radial Velocity                  1989
Transit                          2002
Transit Timing Variations        2011
Name: year, dtype: int64

In [27]:
planets.groupby("method")["year"].describe()

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,2011.500000,2.121320,2010.0,2010.75,2011.5,2012.25,2013.0
Eclipse Timing Variations,9.0,2010.000000,1.414214,2008.0,2009.00,2010.0,2011.00,2012.0
Imaging,38.0,2009.131579,2.781901,2004.0,2008.00,2009.0,2011.00,2013.0
Microlensing,23.0,2009.782609,2.859697,2004.0,2008.00,2010.0,2012.00,2013.0
Orbital Brightness Modulation,3.0,2011.666667,1.154701,2011.0,2011.00,2011.0,2012.00,2013.0
Pulsar Timing,5.0,1998.400000,8.384510,1992.0,1992.00,1994.0,2003.00,2011.0
Pulsation Timing Variations,1.0,2007.000000,NaN,2007.0,2007.00,2007.0,2007.00,2007.0
Radial Velocity,553.0,2007.518987,4.249052,1989.0,2005.00,2009.0,2011.00,2014.0
Transit,397.0,2011.236776,2.077867,2002.0,2010.00,2012.0,2013.00,2014.0
Transit Timing Variations,4.0,2012.500000,1.290994,2011.0,2011.75,2012.5,2013.25,2014.0

In [28]:
# VECTOR: Vamos a crear el vector decada

In [29]:
decada = 10 * (planets["year"]//10)
# cociente de la división entera con "//"
decada

0       2000
1       2000
2       2010
3       2000
4       2000
        ...
1030    2000
1031    2000
1032    2000
1033    2000
1034    2000
Name: year, Length: 1035, dtype: int64

In [36]:
decada = "dec " + decada.astype(str)
decada.name = "decada"
decada

0       dec dec2000
1       dec dec2000
2       dec dec2010
3       dec dec2000
4       dec dec2000
           ...
1030    dec dec2000
1031    dec dec2000
1032    dec dec2000
1033    dec dec2000
1034    dec dec2000
Name: decada, Length: 1035, dtype: object

In [37]:
decada.describe()

count            1035
unique              4
top       dec dec2010
freq              597
Name: decada, dtype: object

In [38]:
# Vamos a analizar el número de descubrimientos por método y década

In [42]:
planets.groupby(["method", decada])["number"].sum()

method                         decada
Astrometry                     dec dec2010      2
Eclipse Timing Variations      dec dec2000      5
                               dec dec2010     10
Imaging                        dec dec2000     29
                               dec dec2010     21
Microlensing                   dec dec2000     12
                               dec dec2010     15
Orbital Brightness Modulation  dec dec2010      5
Pulsar Timing                  dec dec1990      9
                               dec dec2000      1
                               dec dec2010      1
Pulsation Timing Variations    dec dec2000      1
Radial Velocity                dec dec1980      1
                               dec dec1990     52
                               dec dec2000    475
                               dec dec2010    424
Transit                        dec dec2000     64
                               dec dec2010    712
Transit Timing Variations      dec dec2010      9
Name: number, dtype: int64

In [43]:
planets.groupby(["method", decada])["number"].sum().unstack()

decada,dec dec1980,dec dec1990,dec dec2000,dec dec2010
method,,,,
Astrometry,NaN,NaN,NaN,2.0
Eclipse Timing Variations,NaN,NaN,5.0,10.0
Imaging,NaN,NaN,29.0,21.0
Microlensing,NaN,NaN,12.0,15.0
Orbital Brightness Modulation,NaN,NaN,NaN,5.0
Pulsar Timing,NaN,9.0,1.0,1.0
Pulsation Timing Variations,NaN,NaN,1.0,NaN
Radial Velocity,1.0,52.0,475.0,424.0
Transit,NaN,NaN,64.0,712.0
Transit Timing Variations,NaN,NaN,NaN,9.0

In [59]:
planets.groupby(["method", decada])["number"].sum().unstack().fillna('-') # Rellenamos los NAN con un 0

decada                        dec dec1980 dec dec1990 dec dec2000 dec dec2010
method
Astrometry                              -           -           -         2.0
Eclipse Timing Variations               -           -         5.0        10.0
Imaging                                 -           -        29.0        21.0
Microlensing                            -           -        12.0        15.0
Orbital Brightness Modulation           -           -           -         5.0
Pulsar Timing                           -         9.0         1.0         1.0
Pulsation Timing Variations             -           -         1.0           -
Radial Velocity                       1.0        52.0       475.0       424.0
Transit                                 -           -        64.0       712.0
Transit Timing Variations               -           -           -         9.0

# EJERCICIO 1
hacer un estudio y analizar la variable masa para cada método.
Ver si la masa de los planetas descubiertos depende del método utilizado.

In [53]:
planets.groupby("method")["mass"].describe().fillna(0)

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,0.0,0.000000,0.000000,0.0000,0.00000,0.000,0.0000,0.00
Eclipse Timing Variations,2.0,5.125000,1.308148,4.2000,4.66250,5.125,5.5875,6.05
Imaging,0.0,0.000000,0.000000,0.0000,0.00000,0.000,0.0000,0.00
Microlensing,0.0,0.000000,0.000000,0.0000,0.00000,0.000,0.0000,0.00
Orbital Brightness Modulation,0.0,0.000000,0.000000,0.0000,0.00000,0.000,0.0000,0.00
Pulsar Timing,0.0,0.000000,0.000000,0.0000,0.00000,0.000,0.0000,0.00
Pulsation Timing Variations,0.0,0.000000,0.000000,0.0000,0.00000,0.000,0.0000,0.00
Radial Velocity,510.0,2.630699,3.825883,0.0036,0.22525,1.260,3.0000,25.00
Transit,1.0,1.470000,0.000000,1.4700,1.47000,1.470,1.4700,1.47
Transit Timing Variations,0.0,0.000000,0.000000,0.0000,0.00000,0.000,0.0000,0.00

In [54]:
planets.groupby(["method", decada])["mass"].sum().unstack().fillna(0) # Rellenamos los NAN con un 0

decada,dec dec1980,dec dec1990,dec dec2000,dec dec2010
method,,,,
Astrometry,0.00,0.0000,0.00000,0.0000
Eclipse Timing Variations,0.00,0.0000,6.05000,4.2000
Imaging,0.00,0.0000,0.00000,0.0000
Microlensing,0.00,0.0000,0.00000,0.0000
Orbital Brightness Modulation,0.00,0.0000,0.00000,0.0000
Pulsar Timing,0.00,0.0000,0.00000,0.0000
Pulsation Timing Variations,0.00,0.0000,0.00000,0.0000
Radial Velocity,11.68,68.1782,945.31928,316.4789
Transit,0.00,0.0000,0.00000,1.4700
Transit Timing Variations,0.00,0.0000,0.00000,0.0000